micronaut:
  application:
    name: keymanagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/mysql-keymanager-rpc
    driverClassName: com.mysql.cj.jdbc.Driver
    username: keymanager-rpc
    password: 123
    schema-generate: create-drop
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true