micronaut:
  application:
    name: keymanagerGrpc

datasources:
  default:
    url: '${DB_URI:`jdbc:mysql://localhost:3306/mysql-keymanager-rpc`}'
    username: '${DB_USER:keymanager-rpc}'
    password: '${DB_PASSWORD:123}'
    dialect: '${DB_DIALECT:MYSQL}'
#    driverClassName: com.mysql.cj.jdbc.Driver
#    schema-generate: create-drop

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true

itau:
  contas:
    url: '${ITAU_URL:`http://localhost:9091/api/v1`}'

bcb:
  pix:
    url: '${BCB_URL:`http://localhost:8082/api/v1/pix/keys`}'